"""empty message

Revision ID: 404e70953277
Revises: c3a2c2237ab5
Create Date: 2024-12-27 17:30:27.579573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404e70953277'
down_revision = 'c3a2c2237ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateStart', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.Date(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('endDate')
        batch_op.drop_column('dateStart')

    # ### end Alembic commands ###
