"""empty message

Revision ID: 72629d582448
Revises: d54236002492
Create Date: 2024-10-14 21:40:09.430558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72629d582448'
down_revision = 'd54236002492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
