"""empty message

Revision ID: c3a2c2237ab5
Revises: 46ed2bd894fe
Create Date: 2024-12-27 17:26:35.760958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a2c2237ab5'
down_revision = '46ed2bd894fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateStart', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.Date(), nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('endDate')
        batch_op.drop_column('dateStart')

    # ### end Alembic commands ###
